### PR TITLE
Add audio support to homebridge-doorbird.

### PR DESCRIPTION
**Pull request by hjdhjd**
Audio support for homebridge-doorbird.

There are prerequisites:

* ffmpeg must be compiled with fdk-aac support. Without this, ffmpeg can't encode to AAC which is needed for HomeKit.

* config.json needs to have a new setting in the videoConfig section:
```
"audio" : true
```

* config.json needs to have the following in the source section for videoConfig:
```
"source": "-re -rtsp_transport tcp -i rtsp://doorbirduser:doorbirdpass@doorbirdip:8557/mpeg/media.amp -f mulaw -ar 8000 -i http://doorbirduser:doorbirdpass@doorbirdip/bha-api/audio-receive.cgi""source": "-re -rtsp_transport tcp -i rtsp://doorbirduser:doorbirdpass@doorbirdip:8557/mpeg/media.amp -f mulaw -ar 8000 -i http://doorbirduser:doorbirdpass@doorbirdip/bha-api/audio-receive.cgi"
```

If you add this without a properly working ffmpeg, you won't be able to stream anything because of the lack of AAC support.

Enjoy!

### CODE REVIEW

**Comment by brownad** [comment]
Awesome

I’ll take a look to merge a bit later.. but brilliant commit

**Comment by hjdhjd** [comment]
@brownad - a broader suggestion. Simplify configuration of this plugin.

What the average person shouldn't need to specify the `source` line, etc.

It should just be:

```
"doorbird" : "doorbirdip"
"username": "someuser" 
"password": "some pass"
"audio" : true
```

If someone wants to specify the `videoConfig` block to customize their own systems, they can. But really...this should be pretty close to automated for most people otherwise so it "just works" for most people out of the box, so to speak.

What do you think?

**Comment by brownad** [comment]
I’m all up for simplifying this plugin.  If you have a design that you want to change I’ll take it in. The docs would have to reflect a breaking change that’s all.

Sorry haven’t merged the audio yet..

**Comment by brownad** [comment]
Some docs to update before I publish to npm

**Comment by hjdhjd** [comment]
No worries. I’ll take on simplifying it after you push this update. Figure we’re overdue for some housecleaning. I’ll probably take on simplifying and cleaning up configuration and then mess around with microphone support.

**Comment by brownad** [comment]
> @brownad - a broader suggestion. Simplify configuration of this plugin.
> 
> What the average person shouldn't need to specify the `source` line, etc.
> 
> It should just be:
> 
> ```
> "doorbird" : "doorbirdip"
> "username": "someuser" 
> "password": "some pass"
> "audio" : true
> ```
> 
> If someone wants to specify the `videoConfig` block to customize their own systems, they can. But really...this should be pretty close to automated for most people otherwise so it "just works" for most people out of the box, so to speak.
> 
> What do you think?

I remember making it configurable as back then RTSP was super unreliable, so I made the video option completely open to use whatever stream you had for DoorBird; MJPEG, RTSP, local NVR, iSpyConnect... however given the audio is now a 1st class item think you're right it should just default to RTSP and hide the info away.

**Comment by brownad** [comment]
This would be good idea as a dependency: to make audio easier
https://www.npmjs.com/package/ffmpeg-for-homebridge

**Comment by hjdhjd** [comment]
Yep. I've incorporated it into my own plugins. The catch is you can't guarantee every platform, so you'll still need to make sure you're in good shape. I'll take a pass at simplifying a bunch of this in the coming days...and then we can turn attention to microphone support.

Honestly, if we can get it all going, it would be a superior UX to the native Doorbird app, at least in my world.

**Comment by brownad** [comment]
Cool… :)

**Pull request merged**
