### PR TITLE
doorbird-ng

### PR DESCRIPTION
**Pull request by hjdhjd**
This should merge cleanly. README updates, user configuration simplification, light and motion bug fixes, ffmpeg simplification for users, and more.

### CODE REVIEW

**Comment by hjdhjd** [comment]
Try this @brownad

**Comment by brownad** [comment]
Publishing...

**Comment by hjdhjd** [comment]
Terrific. You publishing an updated npm too?

**Comment by brownad** [comment]
yep

**Comment by brownad** [comment]
hmm plugin bombs out on my setup

**Comment by hjdhjd** [comment]
Just installed from npm and it works fine. what's the bombing you're seeing?

**Comment by hjdhjd** [comment]
One thing that may be needed is to uninstall and reinstall the plugin with --unsafe-perm. ffmpeg-for-homebridge requires it in order to make the prebuilt ffmpeg functional.

**Comment by axelbrunger** [comment]
My homebridge does not work anymore after installing the latest version of Doorbird plugin. How do I uninstall and then reinstall?

On Jun 1, 2020, at 2:42 PM, hjdhjd <notifications@github.com<mailto:notifications@github.com>> wrote:



One thing that may be needed is to uninstall and reinstall the plugin with --unsafe-perm. ffmpeg-for-homebridge requires it in order to make the prebuilt ffmpeg functional.

**Comment by hjdhjd** [comment]
`npm -g uninstall homebridge-doorbird
`
then

`npm -g --unsafe-perm install homebridge-doorbird
`

**Comment by brownad** [comment]
didn’t work for me

**Comment by hjdhjd** [comment]
What's the issue you're running into?

**Comment by brownad** [comment]
just the doorbird plugin is unresponsive, no error logs. tried the clean removal / re-install

**Comment by hjdhjd** [comment]
What’s your config.json? Config options have changed.

**Comment by hjdhjd** [comment]
And unresponsive as in...the sensors don’t work, or the video won’t stream? Two different problems there...if it’s the latter, I have a hunch what it is.

**Comment by hjdhjd** [comment]
If the video won’t stream try setting additionalCommandline to “-tune zerolatency” in your config.json and see if that fixes it. It’s a pretty conservative setting.

**Comment by brownad** [comment]
Doesn’t stream, nor do sensors respond:

       {
           "platform": "DoorBird",
           "name": "Doorbird",

           "controllers": [
             {
               "doorbird": "192.168.0.10",
               "username": “xxxx",
               "password": “xxxx",
               "audio": "true"
             }
           ]
        }

**Comment by hjdhjd** [comment]
Crap. Typo. Substitute cameras for controllers in your config.

See below:

        {
            "platform" : "DoorBird",
            "name": "Doorbird",

            "cameras" : [
              {
                "doorbird": "192.168.1.2",
                "username": "user",
                "password": "pass",
                "audio": true
              }
            ]
        },

**Comment by hjdhjd** [comment]
Edited the above...see if that does the trick

**Comment by hjdhjd** [comment]
Did that do the trick?

**Comment by brownad** [comment]
going to clean out then try again. won't be until tomorrow

**Comment by hjdhjd** [comment]
Cheers.

**Comment by axelbrunger** [comment]
Thanks. I ended up restoring the older homebridge plugin as of yesterday.  Let me know when it is safe
to try updating again.

On Jun 1, 2020, at 2:53 PM, hjdhjd <notifications@github.com<mailto:notifications@github.com>> wrote:



npm -g uninstall homebridge-doorbird
then

npm -g --unsafe-perm install homebridge-doorbird

**Comment by hjdhjd** [comment]
It is safe. The configuration options have changed. There was a typo in the README file. If / when you want to reinstall, do so, but read the README before you do. Thanks.

**Comment by axelbrunger** [comment]
One step forward. Homebridge is running again, but in Apple Homekit it says that the Doorbird is not responding. Do I need to redo the Homekit pairing?

On Jun 1, 2020, at 7:35 PM, hjdhjd <notifications@github.com<mailto:notifications@github.com>> wrote:



It is safe. The configuration options have changed. There was a typo in the README file. If / when you want to reinstall, do so, but read the README before you do. Thanks.

**Comment by axelbrunger** [comment]
I went back to the previous version and awaiting further instructions how to get the new version to work with Apple Homekit

On Jun 1, 2020, at 7:54 PM, Axel T Brunger <brunger@stanford.edu<mailto:brunger@stanford.edu>> wrote:

One step forward. Homebridge is running again, but in Apple Homekit it says that the Doorbird is not responding. Do I need to redo the Homekit pairing?

On Jun 1, 2020, at 7:35 PM, hjdhjd <notifications@github.com<mailto:notifications@github.com>> wrote:



It is safe. The configuration options have changed. There was a typo in the README file. If / when you want to reinstall, do so, but read the README before you do. Thanks.

**Comment by hjdhjd** [comment]
Please see the README. There was a typo in the prior version with respect to config.json. The readme at: https://github.com/brownad/homebridge-doorbird should be accurate now. If you're having issues, post your config.json and I'll help you troubleshoot.

Thanks.

**Comment by axelbrunger** [comment]
I exactly followed these instructions, the homebridge was up and running, I could control the DoorBird from the Accessories page of the Homebridge GUI.

But Apple Homekit was unable to connect to the DoorBird. Please advise.

Attached is the config file (passwords, etc deleted).




On Jun 1, 2020, at 8:36 PM, hjdhjd <notifications@github.com<mailto:notifications@github.com>> wrote:



Please see the README. There was a typo in the prior version with respect to config.json. The readme at: https://github.com/brownad/homebridge-doorbird should be accurate now. If you're having issues, post your config.json and I'll help you troubleshoot.

Thanks.

**Comment by hjdhjd** [comment]
It didn't come across. Can you please paste the relevant portion of the config.json here?

**Comment by axelbrunger** [comment]
here we go:



{
    "bridge": {
        "name": "Homebridge",
        "username": "",
        "port": ,
        "pin": ""
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "log": {
                "method": "file",
                "path": "/Users/admin/.homebridge/homebridge.log"
            },
            "platform": "config"
        },
        {
            "platform": "DoorBird",
            "name": "Doorbird",
            "cameras": [
                {
                    "doorbird": "",
                    "username": "",
                    "password": "",
                    "audio": "true"
                }
            ]
        },
        {
            "name": "Nest",
            "googleAuth": {
                "issueToken":
            },
            "structureId": "",
            "options": [
                "HomeAway.AsOccupancySensor",
                "Thermostat.Eco.Disable",
                "Thermostat.Fan.Disable",
                "Protect.Disable"
            ],
            "platform": "Nest"
        }
    ]
}


On Jun 1, 2020, at 8:58 PM, hjdhjd <notifications@github.com<mailto:notifications@github.com>> wrote:



It didn't come across. Can you please paste the relevant portion of the config.json here?

**Comment by hjdhjd** [comment]
Thanks. Try adding an additional name variable under the cameras block like so:

```js
            "cameras": [
                {
                    "name": "",
                    "doorbird": "",
                    "username": "",
                    ...
```

Let me know if that does the trick.

**Comment by axelbrunger** [comment]
No. Sorry. That doesn’t work either. It says “No Response” when I click on the various DoorBird accessories within HomeKit.



On Jun 1, 2020, at 10:11 PM, hjdhjd <notifications@github.com<mailto:notifications@github.com>> wrote:



Thanks. Try adding an additional name variable under the cameras block like so:

            "cameras": [
                {
                    "name": "",
                    "doorbird": "",
                    "username": "",
                    ...

Let me know if that does the trick.

**Comment by axelbrunger** [comment]
Take that back. The name had to be exactly “DoorBird”. Previously, I used “Doorbird” and that didn’t work!

But now the audio doesn’t work anymore!




On Jun 1, 2020, at 10:18 PM, Axel T Brunger <brunger@stanford.edu<mailto:brunger@stanford.edu>> wrote:

No. Sorry. That doesn’t work either. It says “No Response” when I click on the various DoorBird accessories within HomeKit.



On Jun 1, 2020, at 10:11 PM, hjdhjd <notifications@github.com<mailto:notifications@github.com>> wrote:



Thanks. Try adding an additional name variable under the cameras block like so:

            "cameras": [
                {
                    "name": "",
                    "doorbird": "",
                    "username": "",
                    ...

Let me know if that does the trick.

**Comment by axelbrunger** [comment]
This is the latest config that works EXCEPT for the audio (this worked in the previous version!)

 {
            "platform": "DoorBird",
            "name": "Doorbird",
            "cameras": [
                {
                    "name": "DoorBird",
                    "doorbird": “xxx",
                    "username": “xxx",
                    "password": “xxx",
                    "audio": "true"
                }
            ]
        },

On Jun 1, 2020, at 10:24 PM, Axel T Brunger <brunger@stanford.edu<mailto:brunger@stanford.edu>> wrote:

Take that back. The name had to be exactly “DoorBird”. Previously, I used “Doorbird” and that didn’t work!

But now the audio doesn’t work anymore!




On Jun 1, 2020, at 10:18 PM, Axel T Brunger <brunger@stanford.edu<mailto:brunger@stanford.edu>> wrote:

No. Sorry. That doesn’t work either. It says “No Response” when I click on the various DoorBird accessories within HomeKit.



On Jun 1, 2020, at 10:11 PM, hjdhjd <notifications@github.com<mailto:notifications@github.com>> wrote:



Thanks. Try adding an additional name variable under the cameras block like so:

            "cameras": [
                {
                    "name": "",
                    "doorbird": "",
                    "username": "",
                    ...

Let me know if that does the trick.

**Comment by hjdhjd** [comment]
One thing at a time. :)

Post your current config.

The name thing...it’s a bug, but not a bug at the same time methinks.

If you’re willing to bear with me for a few minutes...try removing that name block out of cameras, shutdown homebridge, and delete your accessories cache in homebridge, and then restart.

Would you mind trying that?

**Comment by axelbrunger** [comment]
How do I delete the accessories cache in homebridge?


On Jun 1, 2020, at 10:29 PM, hjdhjd <notifications@github.com> wrote:

﻿

One thing at a time. :)

Post your current config.

The name thing...it’s a bug, but not a bug at the same time methinks.

If you’re willing to bear with me for a few minutes...try removing that name block out of cameras, shutdown homebridge, and delete your accessories cache in homebridge, and then restart.

Would you mind trying that?

**Comment by hjdhjd** [comment]
I think I’ve got a handle on it...let me investigate on my end further, but for the time being, you’ve got your workaround. :)

**Comment by axelbrunger** [comment]
Sure. I can live without the audio for a while ;-)


On Jun 1, 2020, at 10:49 PM, hjdhjd <notifications@github.com> wrote:

﻿

I think I’ve got a handle on it...let me investigate on my end further, but for the time being, you’ve got your workaround. :)

**Comment by brownad** [comment]
Tried multiple times same result

Removed camera, attempted to add back in with version 0.1.0  failed to discover doorbird
Removed homebridge, cleaned cache and accessories attempted to add doorbird on 0.1.0 failed to discover it
Removed homebridge, started with 0.0.9 succeed to add, then upgraded to 0.1.0, failed as before, sensors were again unresponsive and no video stream

**Comment by hjdhjd** [comment]
I'll come back to this in a few hours...but here's the missing piece for you @brownad - I believe there's a HomeKit limitation as it relates to names we've inadvertently run into. I'll finish the proper fix tomorrow.

Clear out the caches / accessories, configure the block like so...

```
 {
            "platform": "DoorBird",
            "name": "Doorbird",
            "cameras": [
                {
                    "name": "DoorBird",
                    "doorbird": “xxx",
                    "username": “xxx",
                    "password": “xxx",
                    "audio": "true"
                }
            ]
},

```

That should do it...for now.

**Comment by brownad** [comment]
Back in business, i didn’t need to remove / clean anything just the below was enough to upgrade

Nice one :) docs getting an update now

**Comment by axelbrunger** [comment]
Have you fixed the issue? Is it safe to try again?

By the way, how do I clear the Homebridge accessory caches as you had mentioned in a previous email?

On Jun 2, 2020, at 1:58 AM, hjdhjd <notifications@github.com<mailto:notifications@github.com>> wrote:



I'll come back to this in a few hours...but here's the missing piece for you @brownad<https://github.com/brownad> - I believe there's a HomeKit limitation as it relates to names we've inadvertently run into. I'll finish the proper fix tomorrow.

Clear out the caches / accessories, configure the block like so...

 {
            "platform": "DoorBird",
            "name": "Doorbird",
            "cameras": [
                {
                    "name": "DoorBird",
                    "doorbird": “xxx",
                    "username": “xxx",
                    "password": “xxx",
                    "audio": "true"
                }
            ]
},



That should do it...for now.

**Comment by brownad** [comment]
I was able to after updating the config correctly.  Docs on README are correct now.

Suggest the uninstall of the old plugin and upgrade with command provided on the docs also.  The clear out of /persist and /accessories shouldn’t be required, although I had tested it just in case.  I was able to install older version (0.0.9) then move up to 0.1.x without a problem, it was a very subtle config change.

Check the docs and let us know.

**Comment by axelbrunger** [comment]
OK. I did all this, but audio does not work anymore!

On Jun 2, 2020, at 8:20 AM, brownad <notifications@github.com<mailto:notifications@github.com>> wrote:


I was able to after updating the config correctly. Docs on README are correct now.

Suggest the uninstall of the old plugin and upgrade with command provided on the docs also. The clear out of /persist and /accessories shouldn’t be required, although I had tested it just in case. I was able to install older version (0.0.9) then move up to 0.1.x without a problem, it was a very subtle config change.

Check the docs and let us know.

**Comment by axelbrunger** [comment]
Also, the video stops after about half a minute. Definitely still problems with this new version!

I’m going back to old version!

On Jun 2, 2020, at 8:32 AM, brunger <brunger@stanford.edu<mailto:brunger@stanford.edu>> wrote:

OK. I did all this, but audio does not work anymore!

On Jun 2, 2020, at 8:20 AM, brownad <notifications@github.com<mailto:notifications@github.com>> wrote:


I was able to after updating the config correctly. Docs on README are correct now.

Suggest the uninstall of the old plugin and upgrade with command provided on the docs also. The clear out of /persist and /accessories shouldn’t be required, although I had tested it just in case. I was able to install older version (0.0.9) then move up to 0.1.x without a problem, it was a very subtle config change.

Check the docs and let us know.

**Comment by brownad** [comment]
Might be a question for @hjdhjd then.  I’ve been running and testing the latest with a video stream open for last hour.  With a couple of devices polling the video occasionally.  Running homebridge on Windows 10.

So you’re over the unresponsive sensors then, just the video cuts off prematurely?

**Comment by axelbrunger** [comment]
Video just cuts off and there is no audio. When I go back to the previous version of the DoorBird plugin, everything is fine.


On Jun 2, 2020, at 9:08 AM, brownad <notifications@github.com<mailto:notifications@github.com>> wrote:


Might be a question for @hjdhjd then. I’ve been running and testing the latest with a video stream open for last hour. With a couple of devices polling the video occasionally. Running homebridge on Windows 10.

So you’re over the unresponsive sensors then, just the video cuts off prematurely?

**Pull request merged**
