### PR TITLE
Doorbird ng

### PR DESCRIPTION
**Pull request by hjdhjd**
@brownad - big update here.

I restructured parts of the plugin here for readability and fixed a few bugs along the way. I've simplified user configuration for the plugin.

- FFmpeg autoconfiguration, if available, is now used. No user intervention needed on supported OSs.
- Updated many of the configuration parameters and simplified the setup.
- Updated README to reflect the above.
- Fixed some bugs with the way the motion sensor and lights were triggered and reset.
- Updated the ffmpeg.js to the latest from homebridge-camera-ffmpeg, though I removed Google Drive support because I view it as non-core to this plugin.
- Simplified audio configuration.
- Added manufacturer and serial information from the Doorbird.

There's a lot that I touched and mucked with. I've been running this for a few days without issue. Give it a whirl.

### CODE REVIEW

**Comment by brownad** [comment]
Wow!

Ok I’m on it tonight

**Comment by hjdhjd** [comment]
Yeah...it started small, and then I just kept going. :)

Some cool stuff for the future in here too. Once we get this one merged in and live, the next rev we can target creating individual relays for activation since I started pulling the config information direct from the Doorbird.

I'd like to get this merged in, and people using it, and then start adding some of the other capabilities. Up next, if I can get the time, is to figure out how to make the microphone work based on how ring and the other apps have taken it on.

The README.md has been completely overhauled in this PR. Take a look as a guidepost for how I approached thinking about the plugin updates I made.

**Comment by brownad** [comment]
Just taking a look now, so much better 🥇.  Do you want to fix the conflicts then I'll merge and publish it tonight.

**Comment by hjdhjd** [comment]
Let me try this again...

**Comment by brownad** [comment]
> Let me try this again...

Np

**Pull request closed without merging**
